name: TypeScript Benchmark
on:
  pull_request:
    paths:
      - ".github/workflows/benchmark.yml"
      - "package.json"
      - "types/**"
      - "benchmarks/typescript/**"
  push:
    branches:
      - master
    paths:
      - ".github/workflows/benchmark.yml"
      - "package.json"
      - "types/**"
      - "benchmarks/typescript/**"
permissions:
  contents: read

jobs:
  typescript:
    runs-on: ubuntu-20.04
    name: Benchmark TypeScript Types
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
        with:
          fetch-depth: 0
      - name: Setup node
        uses: actions/setup-node@0a44ba7841725637a19e28fa30b79a866c81b0a6 # v4.0.4
        with:
          node-version: 16

      - run: npm install

      - run: node ./scripts/create-tarball.js

      - run: npm run ts-benchmark
